- name: List PRs opened in the last month
  shell: bash
  run: |
    echo "PRs opened in the last month:"
    gh pr list --state all \
      --search "created:>=$(date -d '1 month ago' +%Y-%m-%d')" \
      --json number,title,author,createdAt \
      --template $'{{range .}}{{.number}}: {{.title}} (by {{.author.login}}) created on {{.createdAt}}\n{{end}}'   
