name: List Recent PRs

on:
  workflow_dispatch:

jobs:
  list-prs:
    runs-on: ubuntu-latest
    steps:
      - name: List PRs opened in the last month
        run: |
          echo "PRs opened in the last month:"
          gh pr list --state all --search "created:>=$(date -d '1 month ago' +%Y-%m-%d')" --json number,title,author,createdAt --template \
          "{{range .}}{{.number}}: {{.title}} (by {{.author.login}}) created on {{.createdAt}}\n{{end}}"

      - name: List PRs merged in the last month
        run: |
          echo "PRs merged in the last month:"
          gh pr list --state merged --search "merged:>=$(date -d '1 month ago' +%Y-%m-%d')" --json number,title,author,mergedAt --template \
          "{{range .}}{{.number}}: {{.title}} (by {{.author.login}}) merged on {{.mergedAt}}\n{{end}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
